receivers:
  otlp/otelcol:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 200
  batch:

exporters:
  debug:
  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      source: otelcol
  #otlp/jaeger:
  #  endpoint: jaeger-all-in-one:4317
  #  tls:
  #    insecure: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp/otelcol]
      processors: [batch]
      #exporters: [debug, otlp/jaeger, otlp/tempo]
      exporters: [debug, otlp/tempo]
    metrics:
      receivers: [otlp/otelcol]
      processors: [batch]
      exporters: [debug, prometheus]
