# ref: https://ik.am/entries/761
global:
  evaluation_interval: 60s
  scrape_interval: 60s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          alias: 'prometheus'
  - job_name: 'otelcol'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'otelcol:8888' ]  # OpenTelemetry Collector Prometheus exporter
        labels:
          alias: 'otelcol'
      - targets: [ 'otelcol:8889' ]  # OpenTelemetry Metrics Prometheus exporter
        labels:
          alias: 'otel-metrics'
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
        labels:
          alias: 'tempo'
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          alias: 'cadvisor'
