run:
  modules-download-mode: readonly
  allow-parallel-runners: true

# ref. https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - depguard # unnecessary
    - dupl # unnecessary
    - gci # unnecessary
    - goconst # unnecessary
    - godot # unnecessary
    - godox # unnecessary
    - interfacebloat # unnecessary
    - ireturn # NOTE: too many false positives and negatives occur frequently, causing the --fix option to malfunction. So it is disabled.
    - lll # unnecessary
    - nlreturn # ignore "return with no blank line before"
    - nonamedreturns # unnecessary
    - varnamelen # unnecessary
    - wsl # ignore "declarations should never be cuddled"

linters-settings:
  goimports:
    local-prefixes: "github.com/hakadoriya/ormgen"
  wrapcheck:
    ignoreSigs:
      - func errors.New(text string) error
      - func fmt.Errorf(format string, a ...any) error
      - func fmt.Errorf(format string, a ...interface{}) error
      - func github.com/hakadoriya/z.go/errorz.Errorf(format string, a ...interface{}) error

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - canonicalheader
        - containedctx
        - cyclop
        - dupl
        - dupword
        - exhaustruct
        - funlen
        - gochecknoglobals
        - gocognit
        - goconst
        - gocyclo
        - goerr113
        - gosec
        - maintidx
        - noctx
        - revive
        - staticcheck
        - testpackage
        - unused
        - varnamelen
        - wrapcheck
    - # Ignore only internal because not exported
      path: internal/.*\.go
      text: "should have its own declaration"
      linters:
        - revive
