package consts

import (
	"os"
	"time"
)

const (
	AppName                             = "ormgen"
	LanguageGo                          = "go"
	Perm0o775               os.FileMode = 0o775
	DialectPostgres                     = "postgres"
	DialectCockroach                    = "cockroach"
	DialectMySQL                        = "mysql"
	DialectSQLite3                      = "sqlite3"
	DialectSpanner                      = "spanner"
	GeneratedFileHeader                 = `// Code generated by ormgen; DO NOT EDIT.`
	GracefulShutdownTimeout             = 5 * time.Second
)
