// Code generated by ormgen; DO NOT EDIT.
//
// source: group/group.go

package group

func (s *Group) TableName() string {
	return "group"
}

func (s *Group) ColumnsName() []string {
	return []string{"id", "name"}
}

func (s *Group) ColumnName_ID() string {
	return "id"
}

func (s *Group) ColumnName_Name() string {
	return "name"
}

type GroupSlice []*Group

func (s GroupSlice) TableName() string {
	return "group"
}

func (s GroupSlice) ColumnsName() []string {
	return []string{"id", "name"}
}

func (s GroupSlice) ColumnName_ID() string {
	return "id"
}

func (s GroupSlice) ColumnName_Name() string {
	return "name"
}
